### ISSUE TITLE
algorithmic complexity

### ISSUE THREAD

**Issue by itmonk** [Vorago/open-ide#3]
https://github.com/Vorago/open-ide/blob/3cbbf13dfbbe15f25ed551ddbda8ce316e59cd75/main.go#L118
Yeep this is the simple Intersection way but comparison of each element in 'a' to each in 'b' gives us O(n^2) complexity in the end. Put 'b' (at least) into a map O(n). to go through 'b' completely only once and not at each iteration again.

**Comment by Vorago** [comment]
I was aware of that flaw, but went for it anyway in the prototype. Actual number of open windows in any given time is < 100 on my laptop.
Fixed it anyway. Thank you.
